/**
 * @fileoverview gRPC-Web generated client stub for generated
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.24.0-rc3
// source: TwitchBot.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as TwitchBot_pb from './TwitchBot_pb';


export class TwitchBotServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorcheckJoined = new grpcWeb.MethodDescriptor(
    '/generated.TwitchBotService/checkJoined',
    grpcWeb.MethodType.UNARY,
    TwitchBot_pb.CheckJoinedRequest,
    TwitchBot_pb.CheckJoinedRequest,
    (request: TwitchBot_pb.CheckJoinedRequest) => {
      return request.serializeBinary();
    },
    TwitchBot_pb.CheckJoinedRequest.deserializeBinary
  );

  checkJoined(
    request: TwitchBot_pb.CheckJoinedRequest,
    metadata: grpcWeb.Metadata | null): Promise<TwitchBot_pb.CheckJoinedRequest>;

  checkJoined(
    request: TwitchBot_pb.CheckJoinedRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: TwitchBot_pb.CheckJoinedRequest) => void): grpcWeb.ClientReadableStream<TwitchBot_pb.CheckJoinedRequest>;

  checkJoined(
    request: TwitchBot_pb.CheckJoinedRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: TwitchBot_pb.CheckJoinedRequest) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/generated.TwitchBotService/checkJoined',
        request,
        metadata || {},
        this.methodDescriptorcheckJoined,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/generated.TwitchBotService/checkJoined',
    request,
    metadata || {},
    this.methodDescriptorcheckJoined);
  }

}

export class TwitchBotAdminServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptortmiStatus = new grpcWeb.MethodDescriptor(
    '/generated.TwitchBotAdminService/tmiStatus',
    grpcWeb.MethodType.UNARY,
    TwitchBot_pb.TmiStatusRequest,
    TwitchBot_pb.TmiStatusResponse,
    (request: TwitchBot_pb.TmiStatusRequest) => {
      return request.serializeBinary();
    },
    TwitchBot_pb.TmiStatusResponse.deserializeBinary
  );

  tmiStatus(
    request: TwitchBot_pb.TmiStatusRequest,
    metadata: grpcWeb.Metadata | null): Promise<TwitchBot_pb.TmiStatusResponse>;

  tmiStatus(
    request: TwitchBot_pb.TmiStatusRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: TwitchBot_pb.TmiStatusResponse) => void): grpcWeb.ClientReadableStream<TwitchBot_pb.TmiStatusResponse>;

  tmiStatus(
    request: TwitchBot_pb.TmiStatusRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: TwitchBot_pb.TmiStatusResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/generated.TwitchBotAdminService/tmiStatus',
        request,
        metadata || {},
        this.methodDescriptortmiStatus,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/generated.TwitchBotAdminService/tmiStatus',
    request,
    metadata || {},
    this.methodDescriptortmiStatus);
  }

  methodDescriptorstartTmi = new grpcWeb.MethodDescriptor(
    '/generated.TwitchBotAdminService/startTmi',
    grpcWeb.MethodType.UNARY,
    TwitchBot_pb.StartTmiRequest,
    TwitchBot_pb.StartTmiResponse,
    (request: TwitchBot_pb.StartTmiRequest) => {
      return request.serializeBinary();
    },
    TwitchBot_pb.StartTmiResponse.deserializeBinary
  );

  startTmi(
    request: TwitchBot_pb.StartTmiRequest,
    metadata: grpcWeb.Metadata | null): Promise<TwitchBot_pb.StartTmiResponse>;

  startTmi(
    request: TwitchBot_pb.StartTmiRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: TwitchBot_pb.StartTmiResponse) => void): grpcWeb.ClientReadableStream<TwitchBot_pb.StartTmiResponse>;

  startTmi(
    request: TwitchBot_pb.StartTmiRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: TwitchBot_pb.StartTmiResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/generated.TwitchBotAdminService/startTmi',
        request,
        metadata || {},
        this.methodDescriptorstartTmi,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/generated.TwitchBotAdminService/startTmi',
    request,
    metadata || {},
    this.methodDescriptorstartTmi);
  }

  methodDescriptorstopTmi = new grpcWeb.MethodDescriptor(
    '/generated.TwitchBotAdminService/stopTmi',
    grpcWeb.MethodType.UNARY,
    TwitchBot_pb.StopTmiRequest,
    TwitchBot_pb.StopTmiResponse,
    (request: TwitchBot_pb.StopTmiRequest) => {
      return request.serializeBinary();
    },
    TwitchBot_pb.StopTmiResponse.deserializeBinary
  );

  stopTmi(
    request: TwitchBot_pb.StopTmiRequest,
    metadata: grpcWeb.Metadata | null): Promise<TwitchBot_pb.StopTmiResponse>;

  stopTmi(
    request: TwitchBot_pb.StopTmiRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: TwitchBot_pb.StopTmiResponse) => void): grpcWeb.ClientReadableStream<TwitchBot_pb.StopTmiResponse>;

  stopTmi(
    request: TwitchBot_pb.StopTmiRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: TwitchBot_pb.StopTmiResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/generated.TwitchBotAdminService/stopTmi',
        request,
        metadata || {},
        this.methodDescriptorstopTmi,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/generated.TwitchBotAdminService/stopTmi',
    request,
    metadata || {},
    this.methodDescriptorstopTmi);
  }

}

