/**
 * @fileoverview gRPC-Web generated client stub for generated
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.24.0-rc3
// source: Auth.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as Auth_pb from './Auth_pb';


export class LoginServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorlogin = new grpcWeb.MethodDescriptor(
    '/generated.LoginService/login',
    grpcWeb.MethodType.UNARY,
    Auth_pb.LoginRequest,
    Auth_pb.LoginResponse,
    (request: Auth_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    Auth_pb.LoginResponse.deserializeBinary
  );

  login(
    request: Auth_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null): Promise<Auth_pb.LoginResponse>;

  login(
    request: Auth_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Auth_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<Auth_pb.LoginResponse>;

  login(
    request: Auth_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Auth_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/generated.LoginService/login',
        request,
        metadata || {},
        this.methodDescriptorlogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/generated.LoginService/login',
    request,
    metadata || {},
    this.methodDescriptorlogin);
  }

}

