/**
 * @fileoverview gRPC-Web generated client stub for generated
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.24.0-rc3
// source: PingPong.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as PingPong_pb from './PingPong_pb';


export class PingPongServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorping = new grpcWeb.MethodDescriptor(
    '/generated.PingPongService/ping',
    grpcWeb.MethodType.UNARY,
    PingPong_pb.PingRequest,
    PingPong_pb.PongResponse,
    (request: PingPong_pb.PingRequest) => {
      return request.serializeBinary();
    },
    PingPong_pb.PongResponse.deserializeBinary
  );

  ping(
    request: PingPong_pb.PingRequest,
    metadata: grpcWeb.Metadata | null): Promise<PingPong_pb.PongResponse>;

  ping(
    request: PingPong_pb.PingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: PingPong_pb.PongResponse) => void): grpcWeb.ClientReadableStream<PingPong_pb.PongResponse>;

  ping(
    request: PingPong_pb.PingRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: PingPong_pb.PongResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/generated.PingPongService/ping',
        request,
        metadata || {},
        this.methodDescriptorping,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/generated.PingPongService/ping',
    request,
    metadata || {},
    this.methodDescriptorping);
  }

}

